services:
  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    container_name: scheduler-nginx
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src:/var/www/html
    ports:
      - ${NGINX_PORT}:80
    restart: ${DOCKER_RESTART}

  php:
    build: 
      context: ./php
      dockerfile: Dockerfile
    container_name: scheduler-php
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - ./src:/var/www/html
    restart: ${DOCKER_RESTART}

  filebrowser:
    image: filebrowser/filebrowser:s6
    container_name: scheduler-filebrowser
    ports:
      - ${FILEBROWSER_PORT}:80
    volumes:
      - ./src:/srv
      - ./filebrowser/database:/database
      - ./filebrowser/config:/config
    restart: ${DOCKER_RESTART}